# Generated by Django 3.0.6 on 2020-05-04 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(max_length=200, verbose_name='Address Line 1')),
                ('line2', models.CharField(max_length=200, verbose_name='Address Line 2')),
                ('postCode', models.CharField(max_length=200, verbose_name='Postcode')),
                ('googleLocation', models.CharField(max_length=100, verbose_name='Google Location')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitID1', models.CharField(max_length=30, unique=True, verbose_name='Unit ID #1')),
                ('unitID2', models.CharField(max_length=30, unique=True, verbose_name='Unit ID #2')),
                ('locationDescription', models.CharField(max_length=500, verbose_name='Description of Location')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Location', verbose_name='Installation  Location')),
            ],
        ),
    ]
