# Generated by Django 3.0.6 on 2020-05-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='unitID1',
            field=models.CharField(max_length=30, verbose_name='Unit ID #1'),
        ),
        migrations.AlterField(
            model_name='device',
            name='unitID2',
            field=models.CharField(max_length=30, verbose_name='Unit ID #2'),
        ),
    ]
